title: OpenPostbud Docs
description: Dokumentation for OpenPostbud
theme: just-the-docs

baseurl: "/OpenPostbud-docs"
url: "https://itk-dev-rpa.github.io/"

aux_links:
  "OpenPostbud Github": https://github.com/itk-dev-rpa/OpenPostbud

favicon_ico: "📯"